-- 테이블 삭제(초기화용)
DROP TABLE HOMEWORK_INFO;

-- 테이블 생성(생성용)
CREATE TABLE HOMEWORK_INFO
(
	HW_INFO_NUM		INT AUTO_INCREMENT PRIMARY KEY,
    HW_INFO_NAME        VARCHAR(300) NOT NULL,
    HW_INFO_CONTENT     VARCHAR(300) NOT NULL,
    HW_INFO_MENTOR      VARCHAR(50)  NOT NULL,
    HW_INFO_REG_DATE    DATE,
    HW_INFO_DEADLINE    DATE,
    HW_INFO_COMPLETE	INT DEFAULT 0
);

-- 테이블 확인
SELECT*FROM HOMEWORK_INFO;

-- 커밋
COMMIT;
