-- 테이블 초기화 용
DROP TABLE USERS;

-- 테이블 , 시퀀스 생성
CREATE TABLE USERS
(
    USER_IDX    INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STUDY_NUM   INT          DEFAULT 0,
    USER_ROLE   INT          NOT NULL,
    USER_NAME   VARCHAR(30)  NOT NULL,
    USER_ID     VARCHAR(30)  NOT NULL,
    USER_PW     VARCHAR(35)  NOT NULL,
    USER_PW2    VARCHAR(35)  NOT NULL,
    USER_EMAIL  VARCHAR(30)  NOT NULL,
    USER_PHONE  VARCHAR(30)  NOT NULL,
    USER_GENDER INT          NOT NULL,
    USER_SCHOOL VARCHAR(30)  NOT NULL
);

ALTER TABLE USERS
ADD UNIQUE KEY(USER_ID) ;

-- 테이블 확인용
SELECT * FROM USERS;

-- 테스트용 더미
INSERT INTO USERS (
    USER_ROLE, USER_NAME, USER_ID, USER_PW, USER_PW2,
    USER_EMAIL, USER_PHONE, USER_GENDER, USER_SCHOOL)
VALUES ( '1', '멘토', 'mentor', '1234', '1234', 'mentor@com', '010-1111-1111', '1', '멘토대학교');

INSERT INTO USERS (
    USER_ROLE, USER_NAME, USER_ID, USER_PW, USER_PW2,
    USER_EMAIL, USER_PHONE, USER_GENDER, USER_SCHOOL)
VALUES ( '2', '멘티', 'mentee', '1234', '1234', 'mentee@com', '010-2222-2222', '2', '멘티고등학교');

-- 커밋
COMMIT;


UPDATE USERS SET STUDY_NUM=240 WHERE USER_ID='mentee';
